### ISSUE TITLE
Null character string bugfix

### ISSUE THREAD

**Issue by smillerc** [scivision/oo_hdf5_fortran#1]
https://github.com/scivision/oo_hdf5_fortran/blob/7e9c69f74c95f410104fa84c99ad63656d0b37bd/src/read.f90#L23

Since the `hdf_get_string` picks up the null character from the HDF library, I think it would be nice to have the following code (or something like it), strip out the null character. This has tripped up some of my code in the past, since fortran doesn't terminate strings with the null character like C does.

```fortran
subroutine hdf_get_string(self, dname, value)
    class(hdf5_file), intent(in) :: self
    character(*), intent(in) :: dname
    character(*), intent(out) :: value

    integer :: ierr, i

    call h5ltread_dataset_string_f(self%lid, dname, value, ierr)

    do i=1, len(value)
      if (value(i:i) == char(0)) value(i:i) = ' '  ! gets rid of the ^@ character (null)
    end do

    if (ierr /= 0) then
      print*, 'error on dataset ' // dname // ' read ' // self%filename
      error stop
    end if

  end subroutine hdf_get_string
```

**Comment by scivision** [comment]
Thank you!

**Comment by scivision** [comment]
https://github.com/scivision/oo_hdf5_fortran/releases/tag/v1.0.2

Added [`strip_trailing_null` function](https://github.com/scivision/oo_hdf5_fortran/blob/5770651347cdf6105fe20848ee51653acf387a46/src/string_utils.f90#L27)

 I didn't make it always happen in case someone's Fortran program needs the char(0)

```fortran
character(*) :: s1 = 'Hello'//char(0)
character(:), allocatable :: s2

s2 = strip_trailing_null(s1)
```
s2 == 'Hello'
len_trim(s2) == 5

**Comment by scivision** [comment]
This is handled in the latest release, by strip_trailing_null function in src/stringutils.f90

I didn't make it automatic because some people may want the char(0).  So for you, read the string and then run it through the strip_trailing_null()
