### ISSUE TITLE
Get HDF5 library file on Windows 10 x64

### ISSUE THREAD

**Issue by nyckmaia** [scivision/oo_hdf5_fortran#2]
Hi, would like to use you OO-HDF5 interface on Windows environment, but first I think that I will need to compile/build the HDF5-Fortran static library, right?

Well, I tried to do that, but I got some linker errors. 
Could you help me?

**My full question is here:**
https://stackoverflow.com/questions/58171872/hdf5-build-fortran-libraries-windows

**Comment by scivision** [comment]
From your stackoverflow details, you're wanting to use Intel 2019, which is incompatible with Visual Studio 2015. 
To proceed with this setup, one would consider compiling HDF5 from source as per High Performance Mark's answer in the link you provided.

What I did to test on Windows as you probably saw in the README was to use MSYS2. However that won't be of any help when using Intel compilers. If you need OpenMPI on Windows with Fortran, the most natural solution seems to be using Intel compiler, which would again drive one to compile HDF5 from source.

**Comment by scivision** [comment]
https://gist.github.com/scivision/1f9df86de231859c60c1814e1ac76196

I got some C syntax errors that may indicate that HDF Group needs to update their code and/or CMake options to suit Visual Studio 2019.

**Comment by nyckmaia** [comment]
Thank you @scivision

**Comment by scivision** [comment]
@nyckmaia HDF5 1.10.6 supports Visual Studio 2019 and Intel 19 compiler explicitly: https://gamma.hdfgroup.org/ftp/pub/outgoing/hdf5/hdf5-1.10.6-pre1-RELEASE.txt
